-- 코드를 입력하세요
SELECT UGB.TITLE,UGB.BOARD_ID, UGR.REPLY_ID,  UGR.WRITER_ID, UGR.CONTENTS, DATE_FORMAT(UGR.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_BOARD as UGB JOIN USED_GOODS_REPLY as UGR ON UGB.BOARD_ID = UGR.BOARD_ID
WHERE DATE_FORMAT(UGB.CREATED_DATE, '%Y-%m-%d') >= DATE_FORMAT('2022-10-01', '%Y-%m-%d') AND DATE_FORMAT(UGB.CREATED_DATE, '%Y-%m-%d') <= DATE_FORMAT('2022-10-31', '%Y-%m-%d')
ORDER BY DATE_FORMAT(UGR.CREATED_DATE, '%Y-%m-%d'), UGB.TITLE