-- 코드를 입력하세요
SELECT T.USER_ID, T.NICKNAME, T.전체주소, T.전화번호
FROM (SELECT UGU.USER_ID, UGU.NICKNAME, CONCAT(CONCAT(CONCAT(CITY,' ', STREET_ADDRESS1), ' '), STREET_ADDRESS2) as '전체주소', CONCAT(LEFT(TLNO,3), '-', MID(TLNO, 4, 4), '-', RIGHT(TLNO,4)) as '전화번호', COUNT(USER_ID) as COUNT
      FROM USED_GOODS_BOARD as UGB JOIN USED_GOODS_USER as UGU ON UGB.WRITER_ID = UGU.USER_ID
      GROUP BY USER_ID
      ORDER BY USER_ID DESC) as T
WHERE T.COUNT >= 3;

