-- 코드를 입력하세요
SELECT *
FROM (SELECT UGU.USER_ID, UGU.NICKNAME ,SUM(PRICE) AS "TOTAL_SALES"
      FROM USED_GOODS_BOARD UGB JOIN USED_GOODS_USER UGU ON UGB.WRITER_ID = UGU.USER_ID
      WHERE UGB.STATUS = "DONE"
      GROUP BY UGU.USER_ID) as RESULT
WHERE RESULT.TOTAL_SALES >= 700000
ORDER BY RESULT.TOTAL_SALES ASC