-- 코드를 입력하세요
SELECT P.CACD as CATEGORY, COUNT(P.CACD) as PRODUCTS
FROM (SELECT PRODUCT_ID, LEFT(PRODUCT_CODE, 2) as CACD, RIGHT(PRODUCT_CODE, 8) as PRCD, PRODUCT_CODE
      FROM PRODUCT) as P
GROUP BY P.CACD
ORDER BY P.PRCD
