SELECT DISTINCT(CRCRH.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR AS CRCC JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CRCRH ON CRCC.CAR_ID = CRCRH.CAR_ID
WHERE CRCC.CAR_TYPE = '세단' AND DATE_FORMAT(START_DATE, '%Y-%m-%d') BETWEEN '2022-10-01' AND '2022-10-31'
ORDER BY CAR_ID DESC