-- 코드를 입력하세요
SELECT CATEGORY, SUM(SALES) as TOTAL_SALES
FROM (SELECT B.BOOK_ID, B.CATEGORY, BS.SALES
      FROM BOOK as B JOIN BOOK_SALES as BS ON B.BOOK_ID = BS.BOOK_ID
      WHERE BS.SALES_DATE BETWEEN DATE('2022-01-01') AND DATE('2022-01-31')) as S
GROUP BY CATEGORY
ORDER BY CATEGORY